### ISSUE TITLE
tell me about  dir="ltr" in the <html> tag

### ISSUE THREAD

**Issue by njons** [fac-15/kash-portfolio#22]
What's this? what does it do? I have never seen it before! 

<html lang="en" dir="ltr">

**Comment by HStewart23** [comment]
This tag was included because we used the autocomplete tab to finish our code skeleton. It dictates the direction that text is written in (ltr = left to right, you can also do rtl) usually it's obsolete because HTML automatically guesses it possibly based on language. Despite this, it's interesting to know!
